#!/usr/bin/env python3
"""Generate all theme artifacts from theme/colors.json."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


HEX_COLOR = re.compile(r"^#[0-9A-Fa-f]{6}$")
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "theme" / "colors.json"
CSS_TEMPLATE = ROOT / "github" / "github.css.template"


def resolve(colors: dict[str, Any], reference: str) -> str:
    palette_match = re.fullmatch(r"palette\[(\d+)\]", reference)
    if palette_match:
        try:
            value = colors["palette"][int(palette_match.group(1))]
        except (IndexError, KeyError, TypeError) as error:
            raise ValueError(f"invalid palette reference: {reference}") from error
    else:
        value = colors.get(reference)
    if not isinstance(value, str) or not HEX_COLOR.fullmatch(value):
        raise ValueError(f"reference does not resolve to a color: {reference}")
    return value


def load_source() -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError("colors.json must contain an object")

    name = document.get("name")
    colors = document.get("colors")
    roles = document.get("roles")
    if not isinstance(name, str) or not name:
        raise ValueError("colors.json must contain a non-empty name")
    if not isinstance(colors, dict) or not isinstance(roles, dict):
        raise ValueError("colors.json must contain colors and roles objects")

    required = {
        "background",
        "foreground",
        "cursor",
        "cursor_text",
        "selection_background",
        "palette",
    }
    missing = required - colors.keys()
    if missing:
        raise ValueError(f"missing colors: {', '.join(sorted(missing))}")
    palette = colors["palette"]
    if not isinstance(palette, list) or len(palette) != 16:
        raise ValueError("colors.palette must contain exactly 16 colors")
    scalars = [value for key, value in colors.items() if key != "palette"]
    if any(
        not isinstance(value, str) or not HEX_COLOR.fullmatch(value)
        for value in scalars
    ):
        raise ValueError("all scalar colors must be six-digit hex colors")
    if any(
        not isinstance(value, str) or not HEX_COLOR.fullmatch(value)
        for value in palette
    ):
        raise ValueError("all palette entries must be six-digit hex colors")
    for role_name, reference in roles.items():
        if not isinstance(reference, str):
            raise ValueError(f"role {role_name!r} must reference a color")
        resolve(colors, reference)
    return document, colors, roles


def color_role(colors: dict[str, Any], roles: dict[str, Any], name: str) -> str:
    try:
        return resolve(colors, roles[name])
    except KeyError as error:
        raise ValueError(f"missing color role: {name}") from error


def rgb(hex_color: str) -> list[int]:
    return [int(hex_color[index : index + 2], 16) for index in (1, 3, 5)]


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as output_file:
        output_file.write(content)


def write_json(path: Path, document: dict[str, Any]) -> None:
    write_text(
        path, json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )


def ghostty_theme(colors: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/generate-theme.py. Do not edit directly.",
        f"background = {colors['background']}",
        f"foreground = {colors['foreground']}",
        "",
        f"cursor-color = {colors['cursor']}",
        f"cursor-text = {colors['cursor_text']}",
        f"selection-background = {colors['selection_background']}",
        "",
    ]
    lines.extend(
        f"palette = {index}={value}" for index, value in enumerate(colors["palette"])
    )
    return "\n".join(lines) + "\n"


def chrome_manifest(
    document: dict[str, Any], colors: dict[str, Any], roles: dict[str, Any]
) -> dict[str, Any]:
    background = rgb(colors["background"])
    foreground = rgb(colors["foreground_soft"])
    tab_surface = rgb(colors["tab_surface"])
    muted = rgb(color_role(colors, roles, "muted"))
    pink = rgb(color_role(colors, roles, "accent_pink"))
    return {
        "description": "Chrome theme generated from theme/colors.json.",
        "manifest_version": 3,
        "name": f"{document['name'].title()} Chrome Theme",
        "theme": {
            "colors": {
                "bookmark_text": foreground,
                "button_background": foreground,
                "frame": background,
                "frame_inactive": background,
                "background_tab": background,
                "background_tab_inactive": background,
                "ntp_background": background,
                "ntp_header": foreground,
                "ntp_link": pink,
                "ntp_text": foreground,
                "omnibox_background": background,
                "omnibox_text": foreground,
                "tab_background_text": muted,
                "tab_text": pink,
                "toolbar": tab_surface,
                "toolbar_button_icon": foreground,
                "toolbar_text": foreground,
            }
        },
        "version": "1.0.0",
    }


def github_manifest(document: dict[str, Any]) -> dict[str, Any]:
    return {
        "content_scripts": [
            {
                "css": ["github.css"],
                "matches": ["https://github.com/*"],
                "run_at": "document_start",
            }
        ],
        "description": "GitHub dark theme generated from theme/colors.json.",
        "manifest_version": 3,
        "name": f"{document['name'].title()} for GitHub",
        "version": "1.0.0",
    }


def github_css(colors: dict[str, Any], roles: dict[str, Any]) -> str:
    values = {
        "__BACKGROUND__": colors["background"],
        "__FOREGROUND__": colors["foreground"],
        "__SURFACE__": color_role(colors, roles, "surface"),
        "__BORDER__": color_role(colors, roles, "border"),
        "__TAB_SURFACE__": colors["tab_surface"],
        "__CHECKBOX__": colors["checkbox"],
        "__MUTED__": color_role(colors, roles, "muted"),
        "__ACCENT_GREEN__": color_role(colors, roles, "accent_green"),
        "__ACCENT_GREEN_SOFT__": color_role(colors, roles, "accent_green_soft"),
        "__ACCENT_BLUE__": color_role(colors, roles, "accent_blue"),
        "__ACCENT_PINK__": color_role(colors, roles, "accent_pink"),
        "__ACCENT_PURPLE__": color_role(colors, roles, "accent_purple"),
        "__SUCCESS__": color_role(colors, roles, "success"),
        "__DANGER__": color_role(colors, roles, "danger"),
        "__WARNING__": color_role(colors, roles, "warning"),
        "__INFO__": color_role(colors, roles, "info"),
        "__SELECTION__": color_role(colors, roles, "selection"),
    }
    rendered = CSS_TEMPLATE.read_text(encoding="utf-8")
    for placeholder, value in values.items():
        rendered = rendered.replace(placeholder, value)
    if "__" in rendered:
        raise ValueError("github CSS template contains an unreplaced placeholder")
    return (
        "/* Generated by scripts/generate-theme.py. Do not edit directly. */\n"
        + rendered
    )


def main() -> None:
    document, colors, roles = load_source()
    write_text(ROOT / "ghostty" / "themes" / document["name"], ghostty_theme(colors))
    write_json(
        ROOT / "chrome" / "manifest.json", chrome_manifest(document, colors, roles)
    )
    write_json(ROOT / "github" / "manifest.json", github_manifest(document))
    write_text(ROOT / "github" / "github.css", github_css(colors, roles))


if __name__ == "__main__":
    main()
